basePath: /api/1
host: localhost:8080
info:
  contact:
    email: hilmyahmadnaufal@gmail.com
    name: anhilmy
  description: Endpoint SIREG Kegiatan Kategori
  title: SIREG Kegiatan Kategori
  version: "0.1"
paths:
  /:
    get:
      consumes:
      - application/json
      description: do piing
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: Object
      summary: ping example
      tags:
      - example
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
